### ISSUE TITLE
No module named 'typing.io'; 'typing' is not a package

### ISSUE THREAD

**Issue by raffaeler** [Apkawa/xlsx2html#52]
I installed xlsx2html in a brand new virtual environment running on Python 3.13.0 in a Windows 10 VM.

When I run the most basic conversion, I get:
```
> python -m xlsx2html TestSpreadsheet.xlsx TestSpreadsheet.html
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\dev.git\Experiments\AIDataCruncher\AIPythonLibrary\.venv\Lib\site-packages\xlsx2html\__init__.py", line 3, in
 <module>
    from .core import xlsx2html
  File "C:\dev.git\Experiments\AIDataCruncher\AIPythonLibrary\.venv\Lib\site-packages\xlsx2html\core.py", line 19, in <module>
    from xlsx2html.utils.image import bytes_to_datauri
  File "C:\dev.git\Experiments\AIDataCruncher\AIPythonLibrary\.venv\Lib\site-packages\xlsx2html\utils\image.py", line 4, in <module>
    from typing.io import BinaryIO
ModuleNotFoundError: No module named 'typing.io'; 'typing' is not a package
```

**Comment by Apkawa** [comment]
fixed at version 0.6.2
